### PR TITLE
Force price as float, backporting Commerce 4 fix for Commerce 3

### PR DESCRIPTION
**Pull request by boboldehampsink**

### CODE REVIEW

**Comment by boboldehampsink** [comment]
Oops, thought develop was for v3 - is there any v3 branch left?

**Comment by jordikroon** [comment]
Hi @boboldehampsink, Tag v1.x has support for Craft 3. However please be aware that we do not officially support Craft 3 and our v1 anymore.

For your convenience we made a backport patch and it has been released with version [1.1.3](https://github.com/tdeNL/craft-commerce-product-bundles/tree/1.1.3)

**Comment by boboldehampsink** [comment]
@jordikroon Thanks, but I get the following error trying to install 1.1.3:

`tde/craft-commerce-product-bundles 1.1.3 requires craftcms/cms ^4.0 -> found craftcms/cms[4.0.0, ..., 4.5.10] but it conflicts with your root composer.json require (^3.6).`

**Comment by jordikroon** [comment]
@boboldehampsink My bad, I released against the wrong target branch. It should be resolved now.

**Comment by boboldehampsink** [comment]
Thanks!

**Pull request closed without merging**
